/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ranjithlearners.panel;

import com.formdev.flatlaf.FlatClientProperties;
import com.ranjithlearners.connection.MySQL;
import com.ranjithlearners.connection.MySQLProxy;
import com.ranjithlearners.dialog.AddNewExamDate;
import com.ranjithlearners.dialog.AddNewExamResult;
import com.ranjithlearners.dialog.AddNewStudent;
import com.ranjithlearners.gui.HomeScreen;
import com.ranjithlearners.util.AESUtil;
import com.ranjithlearners.util.BackgroundPanel;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akash Weerasinghe
 */
public class ExamResultsPanel extends BackgroundPanel {

    private final HomeScreen homeScreen;
    private final MySQL MySQL = new MySQLProxy();

    public ExamResultsPanel(HomeScreen parent) {
        initComponents();
        this.homeScreen = parent;
        jTabbedPane1.setSelectedIndex(0);
        int selected = jTabbedPane1.getSelectedIndex();
        if (selected == 0) {
            loadWrittenExamData();
        } else if (selected == 1) {
            loadPracticalExamData();
        }

        refreshBtn.putClientProperty(
                FlatClientProperties.STYLE,
                "arc:50; borderColor:#001E3D; borderWidth:2; hoverBackground:#FFA500; foreground:#001E3D"
        );
        addDateBtn.putClientProperty(
                FlatClientProperties.STYLE,
                "arc:50; borderColor:#001E3D; borderWidth:2; hoverBackground:#FFA500; foreground:#001E3D"
        );
        addResultBtn.putClientProperty(
                FlatClientProperties.STYLE,
                "arc:50; borderColor:#001E3D; borderWidth:2; hoverBackground:#FFA500; foreground:#001E3D"
        );
        editBtn.putClientProperty(
                FlatClientProperties.STYLE,
                "arc:50; borderColor:#001E3D; borderWidth:2; hoverBackground:#FFA500; foreground:#001E3D"
        );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        writtenExamTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        practicalExamTable = new javax.swing.JTable();
        addResultBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        addDateBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(830, 645));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Exam Results");

        jTabbedPane1.setBackground(new java.awt.Color(0, 30, 61));

        jPanel1.setBackground(new java.awt.Color(0, 30, 61));

        jScrollPane1.setBackground(new java.awt.Color(0, 30, 61));

        writtenExamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DSR", "Name", "SMRT", "Date", "Result"
            }
        ));
        writtenExamTable.setShowGrid(true);
        jScrollPane1.setViewportView(writtenExamTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Written Exam", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 30, 61));

        jScrollPane2.setBackground(new java.awt.Color(0, 30, 61));

        practicalExamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DSR", "Name", "SMRT", "Vehicle Classes", "Date", "Result"
            }
        ));
        practicalExamTable.setShowGrid(true);
        jScrollPane2.setViewportView(practicalExamTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Practical Exam", jPanel2);

        addResultBtn.setBackground(new java.awt.Color(211, 127, 0));
        addResultBtn.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        addResultBtn.setText("Add new Result");
        addResultBtn.setMargin(new java.awt.Insets(5, 14, 3, 14));
        addResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResultBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(211, 127, 0));
        editBtn.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        editBtn.setText("Edit Results");
        editBtn.setToolTipText("");
        editBtn.setMargin(new java.awt.Insets(5, 14, 3, 14));

        addDateBtn.setBackground(new java.awt.Color(211, 127, 0));
        addDateBtn.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        addDateBtn.setText("Add new Exam Date");
        addDateBtn.setMargin(new java.awt.Insets(5, 14, 3, 14));
        addDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateBtnActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(211, 127, 0));
        refreshBtn.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.setMargin(new java.awt.Insets(5, 14, 3, 14));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addResultBtn)
                    .addComponent(editBtn)
                    .addComponent(addDateBtn)
                    .addComponent(refreshBtn))
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadWrittenExamData() {
        try {
            DefaultTableModel model = (DefaultTableModel) writtenExamTable.getModel();
            model.setRowCount(0);

            String sql = """
            SELECT 
                s.id AS student_id,
                s.name AS student_name,
                swe.written_examination_date AS exam_date,
                swe.status AS exam_status,
                shs.smrt_smrt_no AS smrt_no,
                shs.smrt_yearcode AS smrt_yearcode,
                c.code AS vehicle_class
            FROM student_has_written_examination swe
            JOIN student_has_smrt shs 
              ON swe.student_has_smrt_student_id = shs.student_id
             AND swe.student_has_smrt_smrt_yearcode = shs.smrt_yearcode
             AND swe.student_has_smrt_smrt_smrt_no = shs.smrt_smrt_no
            JOIN student s ON shs.student_id = s.id
            LEFT JOIN student_has_course shc 
              ON s.id = shc.student_id
            LEFT JOIN course c 
              ON shc.course_code = c.code;
        """;

            ResultSet rs = MySQL.executeSearch(sql);

            while (rs.next()) {
                Vector<Object> row = new Vector<>();
                row.add(rs.getString("student_id"));
                row.add(AESUtil.decrypt(rs.getString("student_name")));
                row.add("SMRT/" + rs.getString("smrt_yearcode") + "/" + rs.getString("vehicle_class") + "/" + rs.getString("smrt_no"));
                row.add(rs.getString("exam_date"));
                row.add(rs.getString("exam_status"));
                model.addRow(row);
            }

            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to load written exam data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadPracticalExamData() {
        try {
            DefaultTableModel model = (DefaultTableModel) practicalExamTable.getModel();
            model.setRowCount(0);
            String sql = """
            SELECT 
                s.id AS student_id,
                s.name AS student_name,
                spe.practical_examination_date AS exam_date,
                spe.status AS exam_status,
                shs.smrt_smrt_no AS smrt_no,
                shs.smrt_yearcode AS smrt_yearcode,
                c.code AS vehicle_class
            FROM student_has_practical_examination spe
            JOIN student_has_smrt shs 
              ON spe.student_has_smrt_student_id = shs.student_id
             AND spe.student_has_smrt_smrt_yearcode = shs.smrt_yearcode
             AND spe.student_has_smrt_smrt_smrt_no = shs.smrt_smrt_no
            JOIN student s ON shs.student_id = s.id
            LEFT JOIN student_has_course shc 
              ON s.id = shc.student_id
            LEFT JOIN course c 
              ON shc.course_code = c.code;
        """;

            ResultSet rs = MySQL.executeSearch(sql);

            while (rs.next()) {
                Vector<Object> row = new Vector<>();
                row.add(rs.getString("student_id"));
                row.add(AESUtil.decrypt(rs.getString("student_name")));
                row.add("SM/RT/" + rs.getString("smrt_yearcode") + "/" + rs.getString("vehicle_class") + "/" + rs.getString("smrt_no"));
                row.add(rs.getString("vehicle_class"));
                row.add(rs.getString("exam_date"));
                row.add(rs.getString("exam_status"));
                model.addRow(row);
            }

            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to load practical exam data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void addResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResultBtnActionPerformed
        AddNewExamResult addExam = new AddNewExamResult(this);
        addExam.setLocationRelativeTo(homeScreen);
        addExam.setVisible(true);
    }//GEN-LAST:event_addResultBtnActionPerformed

    private void addDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateBtnActionPerformed
        AddNewExamDate addExamDate = new AddNewExamDate(homeScreen, true);
        addExamDate.setLocationRelativeTo(homeScreen);
        addExamDate.setVisible(true);
    }//GEN-LAST:event_addDateBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        int selected = jTabbedPane1.getSelectedIndex();
        if (selected == 0) {
            loadWrittenExamData();
        } else if (selected == 1) {
            loadPracticalExamData();
        }
    }//GEN-LAST:event_refreshBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDateBtn;
    private javax.swing.JButton addResultBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable practicalExamTable;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable writtenExamTable;
    // End of variables declaration//GEN-END:variables
}
