/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ranjithlearners.panel;

import com.formdev.flatlaf.FlatClientProperties;
import com.ranjithlearners.connection.MySQL;
import com.ranjithlearners.connection.MySQLProxy;
import com.ranjithlearners.util.AESUtil;
import com.ranjithlearners.validation.Validator;
import java.awt.CardLayout;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import raven.toast.Notifications;

/**
 *
 * @author Akash Weerasinghe
 */
public class RegisterPanel extends javax.swing.JPanel {

    private CardLayout contentPanelLayout;
    private JPanel contentPanel;

    public RegisterPanel(CardLayout contentpanellayout, JPanel contentpanel) {
        this.contentPanelLayout = contentpanellayout;
        this.contentPanel = contentpanel;

        initComponents();

        txtRegEmail.putClientProperty(FlatClientProperties.STYLE, "arc:50");
        txtRegPassword.putClientProperty(FlatClientProperties.STYLE, "arc:50");
        registerBtn.putClientProperty(FlatClientProperties.STYLE, "arc:50");
        toggleShowPassword.putClientProperty(FlatClientProperties.STYLE, "arc:50");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toggleShowPassword = new javax.swing.JToggleButton();
        txtRegPassword = new javax.swing.JPasswordField();
        txtRegEmail = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toggleShowPassword.setBackground(new java.awt.Color(0, 30, 61));
        toggleShowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ranjithlearners/img/closed_eye.png"))); // NOI18N
        toggleShowPassword.setBorder(null);
        toggleShowPassword.setBorderPainted(false);
        toggleShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleShowPasswordActionPerformed(evt);
            }
        });
        add(toggleShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 40, 40));

        txtRegPassword.setBackground(new java.awt.Color(0, 30, 61));
        txtRegPassword.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        txtRegPassword.setPreferredSize(new java.awt.Dimension(240, 60));
        add(txtRegPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        txtRegEmail.setBackground(new java.awt.Color(0, 30, 61));
        txtRegEmail.setFont(new java.awt.Font("Bahnschrift", 0, 16)); // NOI18N
        txtRegEmail.setPreferredSize(new java.awt.Dimension(240, 60));
        add(txtRegEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        registerBtn.setBackground(new java.awt.Color(211, 127, 0));
        registerBtn.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(0, 36, 73));
        registerBtn.setText("Register");
        registerBtn.setPreferredSize(new java.awt.Dimension(260, 60));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Log In");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 60, -1));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setText("Alredy have an Account ?");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel6.setText("Password");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel5.setText("Email Address");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 30)); // NOI18N
        jLabel3.setText("Ranjith Driving");
        jLabel3.setPreferredSize(new java.awt.Dimension(220, 50));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 27)); // NOI18N
        jLabel4.setText("Training School");
        jLabel4.setPreferredSize(new java.awt.Dimension(220, 30));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ranjithlearners/img/wheel.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 80));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ranjithlearners/img/login.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.contentPanelLayout.show(contentPanel, "login_panel");
    }//GEN-LAST:event_jLabel8MouseClicked

    private void toggleShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleShowPasswordActionPerformed
        if (toggleShowPassword.isSelected()) {
            txtRegPassword.setEchoChar((char) 0); // Show password
            toggleShowPassword.setIcon(new ImageIcon(getClass().getResource("/com/ranjithlearners/img/eye.png")));
        } else {
            txtRegPassword.setEchoChar('\u2022'); // Mask password
            toggleShowPassword.setIcon(new ImageIcon(getClass().getResource("/com/ranjithlearners/img/closed_eye.png")));
        }
    }//GEN-LAST:event_toggleShowPasswordActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        String email = txtRegEmail.getText().trim();
        String password = String.valueOf(txtRegPassword.getPassword());

        if (!Validator.isEmailValid(email) || !Validator.isPasswordValid(password)) {
            return;
        }

        try {
            String encryptedPassword = AESUtil.encrypt(password);
            MySQL db = new MySQLProxy();

            String checkSql = "SELECT * FROM `admin` WHERE `email` = ?";
            ResultSet rs = db.executeSearch(checkSql, email);

            if (rs.next()) {
                Notifications.getInstance().show(Notifications.Type.ERROR,
                        Notifications.Location.TOP_CENTER,
                        2000,
                        "The Email is Already Registered!");
            } else {
                String insertSql = "INSERT INTO `admin` (`email`, `password`, `status_id`) VALUES (?, ?, 1)";
                db.executeIUD(insertSql, email, encryptedPassword);

                Notifications.getInstance().show(Notifications.Type.SUCCESS,
                        Notifications.Location.TOP_CENTER,
                        2000,
                        "Successfully Registered. Please Proceed to Login");

                this.contentPanelLayout.show(contentPanel, "login_panel");
            }
        } catch (Exception e) {
            throw new RuntimeException(e); // Delegate exception handling to caller
        }
    }//GEN-LAST:event_registerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton registerBtn;
    private javax.swing.JToggleButton toggleShowPassword;
    private javax.swing.JTextField txtRegEmail;
    private javax.swing.JPasswordField txtRegPassword;
    // End of variables declaration//GEN-END:variables
}
